### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by getcontrol** [hackersandslackers/flask-wtform-tutorial#1]
There is no main.py file

**Comment by frMaciek** [comment]
Hi,
You should be able to launch the app without the main.py file.
Please open the app.py and add this section at the end:

```
if __name__ == "__main__":
    app.run()
```

then run the app
`python3 app.py`

**Comment by toddbirchard** [comment]
I originally opted to keep the file structure of this tutorial flat to avoid complexity for beginners, but indeed, the README didn't align with this intent thus had some incorrect instructions.

I went ahead and structured the project to more closely resemble a respectable Flask app, with `wsgi.py` serving as the app entry point.  I've gone ahead and updated the readme as well.

Thanks for pointing this out!
