### ISSUE TITLE
Method not allowed when running example

### ISSUE THREAD

**Issue by Krogsager** [hackersandslackers/flask-wtform-tutorial#4]
When submitting the contact form, an error 405 "Method not allowed" error is returned.

In ´contact.html´ line 10:
`<form method="POST" action="/">`
I thing should have the '/' deleted, so the line is 

```
<form method="POST" action="">
{{ form.csrf_token }}
```
Because it redirects to index.html, which does not accept POST, and the route should lead to success.html any way.

However that gives an odd result when submitting:
`Redirecting...
You should be redirected automatically to target URL: /success. If not click the link.`

How to get rid of the `<h1>Redirecting...</h1>` message and go directly to `success.html`?

**Comment by ARSujonID** [comment]
Inside `flask_wtf_tutorial/routes.py` -

Replace this `return redirect(url_for('success'), code=200)`
With this `return redirect(url_for('success'))`

**Comment by Krogsager** [comment]
Thank you! Removing `code=200` redirects without any interruptions. I'm gonna close this, but can you tell me why `code=200` was added in the first place? What was the point?

**Comment by toddbirchard** [comment]
Thanks for helping out @ARSujonID ! 🥇
