### ISSUE TITLE
requirement Flask-WTF-Tutorial==0.0.1 not found

### ISSUE THREAD

**Issue by BlakeGFitch** [hackersandslackers/flask-wtform-tutorial#5]
Hello and thanks for the tutorial!

Running "pip3 install -r requirements.txt" on ubuntu 18 gets me the following. Any suggestions on how to resolve this would be most appreciated!!

`
File "/home/bgf/flask-wtform-tutorial/myenv/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/flask-wtf-tutorial/`****

**Comment by toddbirchard** [comment]
Oof, the project added itself as a requirement! I've gone ahead and resolved the issue. Let me know if that helps!

**Comment by BlakeGFitch** [comment]
Sounds good! Thanks.
