### ISSUE TITLE
Privacy Error

### ISSUE THREAD

**Issue by BD103** [hackersandslackers/flask-wtform-tutorial#74]
The following error occurs whenever I try to access the [demo](https://flaskwtf.hackersandslackers.app/).

![Your connection is not private](https://user-images.githubusercontent.com/59022059/138870301-ff1248ef-566b-48f0-9f52-405c21207fbc.png)

**Comment by TakeruKondo** [comment]
Hello, What OS? It's CERT_DATE error. Make sure your computers date and time are correct.

https://support.apple.com/en-us/HT203413
https://support.microsoft.com/en-us/windows/how-to-set-your-time-and-time-zone-dfaa7122-479f-5b98-2a7b-fa0b6e01b261#:~:text=In%20Date%20%26%20time%2C%20you%20can,%26%20language%20%3E%20Date%20%26%20time.

**Comment by BD103** [comment]
I realize this issue is pretty old now, and I no longer experience the issue. Closing unless it shows up again.
